// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { codechatBlock } from '.'

export const codechatBlockSchema = parseBlockSchema(codechatBlock)
export const codechatCredentialsSchema = parseBlockCredentials(codechatBlock)
